name: Deploy Production

on:
  push:
    tags: ['v*.*.*']   # Trigger on semantic version tags

jobs:
  promote:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}:prod

      # Alternative: Use ECS deploy if beanstalk deploy is missing
      - name: Deploy to Elastic Beanstalk (alternative)
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: backend/taskdef.json          # Define your task definition here
          service: ai-eyes-prod
          cluster: ai-eyes
          wait-for-service-stability: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
