name: Deploy Expo Web (Staging)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: a.eyes
        run: npm ci

      - name: Export Web
        working-directory: a.eyes
        run: npx expo export --platform web --output-dir dist-web

      - name: Deploy to GitHub Pages (staging)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-staging
          folder: a.eyes/dist-web
          token: ${{ secrets.GITHUB_TOKEN }}
