# .github/workflows/deploy-staging.yml

name: Build Client (Staging)

on:
  push:
    branches:
      - main

permissions:
  contents: read   # only need to read the repo for a build

jobs:
  build:
    name: Install & Build React Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: client
        run: npm install    # no package-lock.json needed

      - name: Build client
        working-directory: client
        run: npm run build

      # ✅ Removed the GitHub Pages deploy step to avoid the permission
      #    error from trying to push as github-actions[bot].
