name: E2E Tests

on:
  workflow_run:
    workflows: [Deploy Staging]
    types: [completed]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:staging   # script that hits staging URL
          wait-on: 'http://staging.myapp.com'
