name: Generate Docs

on:
  push:
    branches: ['**']
  schedule:
    - cron: '0 3 * * 1'    # every Monday 03:00 UTC

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -r docs/requirements.txt
          make -C docs html
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/_build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
