name: Integration Tests

on:
  pull_request:
  workflow_run:
    workflows: [Unit Tests]
    types: [completed]

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      # Check if the requirements.txt file exists before trying to install Python deps
      - name: Install Python deps (if requirements.txt exists)
        run: |
          if [ -f "backend/requirements.txt" ]; then
            pip install -r backend/requirements.txt
          else
            echo "No requirements.txt found, skipping pip install"
          fi

      - name: Start backend (FastAPI) in background
        run: |
          uvicorn backend.app:app --host 0.0.0.0 --port 8000 &

      - name: Run integration tests
        run: npm run test:integration
