# .github/workflows/security-scan.yml

name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 0'   # weekly Sunday 04:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [ 'javascript', 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
