name: Super-Linter

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Super-Linter ships with rules for JS, TS, Python, Markdown, JSON…
      - name: Code Lint
        uses: github/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: turn off languages you don’t use
          # DISABLE_LINTERS: 'RUBY,GO'
