# .github/workflows/superlinter.yml

name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter (via Docker)
        uses: docker://ghcr.io/super-linter/super-linter:slim-v6.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DISABLE_LINTERS: "CHECKOV,JAVASCRIPT_STANDARD,MARKDOWN,PYTHON_BLACK,PYTHON_PYLINT"
